# Generated by Django 4.2.3 on 2023-08-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_7', '0002_rename_advertisements_advertisement'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
