# Generated by Django 4.2.3 on 2023-08-04 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_7', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisements',
            new_name='Advertisement',
        ),
    ]
